packages:
  - packages/*
  - examples/*
  - '!examples/dev-plugin'
  - examples/dev-plugin/*
  - '!examples/dev-sequenced-commands'
  - examples/dev-sequenced-commands/*
  - shims/*

onlyBuiltDependencies:
  - esbuild
  - nx
